name: nardis
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter




  scoped_model: ^1.0.1
  cupertino_icons: ^0.1.2


  intl: ^0.15.7
  intl_translation: ^0.17.4




  flutter_custom_clippers: ^1.0.4
  sqflite: ^1.1.6
  path_provider: ^1.1.0

  angel_framework: ^2.0.4+1
  angel_orm: ^2.0.2
  angel_orm_generator: ^2.0.5
  angel_migration: ^2.0.0


  file: ^5.0.7

  jaguar_orm: ^2.2.6

  bottom_navy_bar: ^2.2.0
  after_layout: ^1.0.7

  dio: ^2.1.3
  bloc: ^0.14.4
  flutter_bloc: ^0.19.0
  equatable: ^0.2.0
  rxdart: ^0.22.0
  image_picker: ^0.6.1+4
  #image_cropper: ^0.0.4
  video_player: 0.10.2+1

  cached_network_image: ^1.0.0
  transparent_image: ^1.0.0
  flutter_advanced_networkimage: ^0.5.0
  package_info: ^0.4.0+6
  floating_search_bar: ^0.2.0
  uuid: ^2.0.2
  flutter_uploader: ^1.0.5+1
  install_plugin: ^2.0.1
  permission_handler: ^3.0.0
  progress_dialog: ^1.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.7.0

  jaguar_query_sqflite: ^2.2.10

  build_runner: ^1.0.0
  simple_animations: ^1.2.0

flutter_icons:
  android: true
  ios: true

dependency_overrides:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iran_sans.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/no_image.png
    - assets/images/user.jpg
    - assets/images/user2.png
    - assets/images/logo_main.jpg
    - assets/images/no_image_available.jpg
    - assets/images/no_profile.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
